AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'policy-change-alert

  An IT automation AWS Step Functions workflow.

  '
Parameters:
  EmailAddress:
    Type: String
    Default: ' '
    Description: (Required) The email address to notify on policy issues.
  restrictedActions:
    Type: String
    Default: s3:DeleteBucket,s3:DeleteObject
    Description: Restricted policy actions
Resources:
  RecieveUserAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://buildersfntwo/8972c646e7cbfb9783c68f720e4d6ddb
      Handler: app.handler
      Runtime: nodejs10.x
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - states:SendTaskSuccess
          Resource: '*'
      Events:
        allow:
          Type: Api
          Properties:
            Path: /allow
            Method: get
        deny:
          Type: Api
          Properties:
            Path: /deny
            Method: get
  ValidatePolicy:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://buildersfntwo/dcc1bbc7a0055817b21011558e9a463d
      Handler: app.handler
      Runtime: nodejs10.x
      Environment:
        Variables:
          restrictedActions:
            Ref: restrictedActions
  PolicyChangerApprove:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://buildersfntwo/cdad586bb18f2776415075e84fa10a88
      Handler: app.handler
      Runtime: nodejs10.x
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - iam:CreatePolicyVersion
          Resource: '*'
      Environment:
        Variables:
          restrictedActions:
            Ref: restrictedActions
  RevertPolicy:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://buildersfntwo/55b4162d3e21fbb74127d4f106b0c285
      Handler: app.handler
      Runtime: nodejs10.x
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - iam:CreatePolicyVersion
          - iam:DeletePolicyVersion
          Resource: '*'
      Environment:
        Variables:
          restrictedActions:
            Ref: restrictedActions
  AskUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://buildersfntwo/9015ae0972566aaf373cbf748816c47c
      Handler: app.handler
      Runtime: nodejs10.x
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - sns:Publish
          Resource: '*'
      Environment:
        Variables:
          restrictedActions:
            Ref: restrictedActions
          Topic:
            Ref: AlertTopic
          APIAllowEndpoint:
            Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/allow
          APIDenyEndpoint:
            Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/deny
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        Fn::Sub: "{\n  \"Comment\": \"Defect detection state machine\",\n  \"StartAt\"\
          : \"ModifyState\",\n  \"States\": {\n    \"ModifyState\": {\n      \"Type\"\
          : \"Pass\",\n      \"Parameters\": {\n        \"policy.$\": \"$.detail.requestParameters.policyDocument\"\
          ,\n        \"accountId.$\": \"$.detail.userIdentity.accountId\",\n     \
          \   \"region.$\": \"$.region\",\n        \"policyMeta.$\":\"$.detail.responseElements.policy\"\
          \n      },\n      \"ResultPath\": \"$\",\n      \"Next\": \"ValidatePolicy\"\
          \n    },\n    \"ValidatePolicy\": {\n      \"Type\": \"Task\",\n      \"\
          ResultPath\":\"$.taskresult\",\n      \"Resource\": \"arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ValidatePolicy}\"\
          ,\n      \"Next\": \"ChooseAction\"\n    },\n    \"TempRemove\": {\n   \
          \   \"Type\": \"Task\",\n      \"ResultPath\":\"$.taskresult\",\n      \"\
          Resource\": \"arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${RevertPolicy}\"\
          ,\n      \"Next\": \"AskUser\"\n    },\n    \"ChooseAction\": {\n      \"\
          Type\" : \"Choice\",\n      \"Choices\": [\n        {\n          \"Variable\"\
          : \"$.taskresult.action\",\n          \"StringEquals\": \"remedy\",\n  \
          \        \"Next\": \"TempRemove\"\n        },\n        {\n          \"Variable\"\
          : \"$.taskresult.action\",\n          \"StringEquals\": \"alert\",\n   \
          \       \"Next\": \"AllowWithNotification\"\n        }\n      ],\n     \
          \ \"Default\": \"AllowWithNotification\"\n    },\n    \"AllowWithNotification\"\
          : {\n      \"Type\": \"Task\",\n      \"Resource\": \"arn:aws:states:::sns:publish\"\
          ,\n      \"Parameters\": {\n        \"TopicArn\": \"${AlertTopic}\",\n \
          \       \"Subject\": \"Policy change detected!\",\n        \"Message.$\"\
          : \"$.taskresult.message\"\n      },\n      \"End\": true\n    },\n    \"\
          AskUser\":{\n        \"Type\": \"Task\",\n        \"Resource\":\"arn:aws:states:::lambda:invoke.waitForTaskToken\"\
          ,\n          \"Parameters\":{  \n              \"FunctionName\":\"askUser\"\
          ,\n              \"Payload\":{  \n                  \"token.$\":\"$$.Task.Token\"\
          \n                }\n          },\n        \"ResultPath\":\"$.taskresult\"\
          ,\n        \"Next\": \"usersChoice\"\n    },\n    \"usersChoice\": {\n \
          \     \"Type\" : \"Choice\",\n      \"Choices\": [\n        {\n        \
          \  \"Variable\": \"$.taskresult.action\",\n          \"StringEquals\": \"\
          delete\",\n          \"Next\": \"denied\"\n        },\n        {\n     \
          \     \"Variable\": \"$.taskresult.action\",\n          \"StringEquals\"\
          : \"allow\",\n          \"Next\": \"approved\"\n        }\n      ],\n  \
          \    \"Default\": \"denied\"\n    },\n    \"denied\": {\n      \"Type\"\
          : \"Pass\",\n      \"End\": true\n    },\n    \"approved\": {\n      \"\
          Type\": \"Task\",\n      \"Resource\": \"arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${PolicyChangerApprove}\"\
          ,              \n      \"End\": true\n    }\n  }\n}"
      RoleArn:
        Fn::GetAtt:
        - StatesExecutionRole
        - Arn
  StatesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - Fn::Sub: states.${AWS::Region}.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: StateMachineTasks
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
              Fn::GetAtt:
              - ValidatePolicy
              - Arn
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
              Fn::GetAtt:
              - AskUser
              - Arn
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
              Fn::GetAtt:
              - RecieveUserAPI
              - Arn
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            - iam:CreatePolicyVersion
            Resource:
              Fn::GetAtt:
              - PolicyChangerApprove
              - Arn
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            - iam:CreatePolicyVersion
            - iam:DeletePolicyVersion
            Resource:
              Fn::GetAtt:
              - RevertPolicy
              - Arn
          - Effect: Allow
            Action:
            - sns:Publish
            Resource:
              Ref: AlertTopic
  CloudwatchEventsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: StartStepFunctions
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - states:StartExecution
            Resource:
              Ref: StateMachine
  IAMEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: NewPolicyCreated
      EventPattern:
        source:
        - aws.iam
        detail-type:
        - AWS API Call via CloudTrail
        detail:
          eventSource:
          - iam.amazonaws.com
          eventName:
          - CreatePolicy
      State: ENABLED
      Targets:
      - Arn:
          Ref: StateMachine
        Id: StateMachineTarget
        RoleArn:
          Fn::GetAtt:
          - CloudwatchEventsExecutionRole
          - Arn
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: alertTopic
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Ref: EmailAddress
      Protocol: Email-JSON
      TopicArn:
        Ref: AlertTopic
Outputs:
  PolicyOrchestratorAPIAllow:
    Description: API Gateway endpoint URL for dev allow function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/allow
  PolicyOrchestratorAPIDeny:
    Description: API Gateway endpoint URL for dev allow function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/deny
